// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelatoriosTI.API.Data;

#nullable disable

namespace RelatoriosTI.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031151001_InitialCreateSqlite")]
    partial class InitialCreateSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("RelatoriosTI.API.Models.DadosRelatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssinaturaUsuarioNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivoPdf")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRenovacaoAntivirus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRenovacaoOffice365")
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MelhoriasFeitas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MelhoriasFeitasConfirmado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MelhoriasProximoMes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoPreventivasIncompletas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutrosContratos")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdLicencasAntivirus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdLicencasOffice365Basic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdLicencasOffice365Standard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdMaquinasPreventivasFeitas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdMaquinasTotal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RelatorioAprovado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumoMes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusPreventivas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tickets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("HotelNome");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("RelatoriosTI.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhAdministrador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoteisPermitidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EhAdministrador = true,
                            Email = "mathaus@admin",
                            HoteisPermitidos = "[]",
                            Senha = "$2a$11$v2YsLtwHrb72xNnvQ4gzoOY527yzeM3XcOSRS.L018TXSHTUjTIGa"
                        });
                });

            modelBuilder.Entity("RelatoriosTI.API.Models.DadosRelatorio", b =>
                {
                    b.HasOne("RelatoriosTI.API.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");
                });
#pragma warning restore 612, 618
        }
    }
}
